on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test-stuff:
    runs-on: ubuntu-22.04
    steps:
      - name: Get merged/open PR labels
        uses: actions/github-script@v7
        id: pr-labels
        with:
          script: |
            let labels = null;
            if (github.eventName === 'push') {
              const resp = await github.rest.pulls.list({
                context.owner,
                context.repo,
                sort: 'updated',
                direction: 'desc',
                state: 'closed',
                per_page: 100
              });
              const merged_pr = resp.data.find(pr => pr.merge_commit_sha === context.sha);
              if (merged_pr) {
                labels = merged_pr.labels;
              }
            }
            else if (github.eventName === 'pull_request') {
              labels = context.payload.pull_request.labels;
            }
            labels = (labels || []).map(l => l.name);
            return labels

      - name: Print result
        run: echo '${{ steps.pr-labels.outputs.result }}'
