on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test-stuff:
    runs-on: ubuntu-22.04
    steps:
      - name: Get merged/open PR labels
        uses: actions/github-script@v7
        id: pr-labels
        with:
          script: |
            let labels = [];
            if (context.eventName === 'push') {
              // api ref: https://octokit.github.io/rest.js/v20#pulls-list
              const resp = await github.rest.pulls.list(
                {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'closed',
                  sort: 'updated',
                  direction: 'desc',
                  per_page: 100,
                }
              );
              const merged_pr = resp.data.find(pr => pr.merge_commit_sha === context.sha);
              labels = merged_pr?.labels;
            }
            else if (context.eventName === 'pull_request') {
              labels = context.payload.pull_request.labels;
            }
            labels = (labels || []).map(l => l.name);
            return labels

      - name: Print result
        run: echo '${{ steps.pr-labels.outputs.result }}'
