on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test-stuff:
    runs-on: ubuntu-22.04
    steps:
      - name: Get merged/open PR labels
        uses: actions/github-script@v7
        id: pr-labels
        with:
          script: |
            let labels = null;
            labels = (labels || []).map(l => l.name);
            return labels

      - name: Print result
        run: echo '${{ steps.pr-labels.outputs.result }}'
